#Copyright (c) 2021, salesforce.com, inc.
#All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause
#For full license text, see the LICENSE file in the repo root or https://#opensource.org/licenses/BSD-3-Clause
# network architecture
# encoder related
elayers: 12
eunits: 2048

# decoder related
dlayers: 6
dunits: 2048

# attention related
adim: 512
aheads: 8
edeath-rate: 0.0
ddeath-rate: 0.0

# streaming setup
streaming_encoder: True
streaming_left_context: 150
streaming_right_context: 0
streaming_block_size: 40
streaming_dec_context: 50

# hybrid CTC/attention
mtlalpha: 0.3

# label smoothing
lsm-weight: 0.1

# minibatch related
batch-size: 12
ngpu: 8
maxlen-in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
opt: noam
accum-grad: 8
grad-clip: 5
patience: 0
epochs: 74
dropout-rate: 0.1


# transformer specific setting
backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr_transformer_stoc:E2E"
transformer-input-layer: conv2d     # encoder architecture type
transformer-lr: 7.5
transformer-warmup-steps: 25000
transformer-attn-dropout-rate: 0.0
transformer-length-normalized-loss: false
transformer-init: pytorch
