#Copyright (c) 2021, salesforce.com, inc.
#All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause
#For full license text, see the LICENSE file in the repo root or https://#opensource.org/licenses/BSD-3-Clause
# network architecture
# encoder related
elayers: 12
eunits: 2048

# decoder related
dlayers: 4
dunits: 2048

# attention related
adim: 512
aheads: 8
edeath-rate: 0.0
ddeath-rate: 0.0

# hybrid CTC/attention
mtlalpha: 0.3

# label smoothing
lsm-weight: 0.1

# minibatch related
batch-size: 20
ngpu: 8
maxlen-in: 512 # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 200 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
opt: noam
accum-grad: 3
grad-clip: 10
patience: 0
epochs: 100
dropout-rate: 0.1

# transformer specific setting
backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr_transformer_realigner:E2E"
transformer-input-layer: conv2d     # encoder architecture type
transformer-lr: 10
transformer-warmup-steps: 25000
transformer-attn-dropout-rate: 0.0
transformer-length-normalized-loss: false
transformer-init: pytorch

report-cer: true