#!/bin/bash

#Copyright (c) 2021, salesforce.com, inc.
#All rights reserved.
#SPDX-License-Identifier: BSD-3-Clause
#For full license text, see the LICENSE file in the repo root or https://#opensource.org/licenses/BSD-3-Clause

# Copyright 2017 Johns Hopkins University (Shinji Watanabe)
#           2020 Salesforce Research (Weiran Wang).
#  Apache 2.0  (http://www.apache.org/licenses/LICENSE-2.0)

. ./path.sh || exit 1;
. ./cmd.sh || exit 1;

# general configuration
backend=pytorch
stage=-1       # start from -1 if you need to start from data download
stop_stage=100
debugmode=1
verbose=0      # verbose option
resume=        # Resume the training from snapshot

# supervised configuration
preprocess_config=conf/specaug_dsl.yaml
train_config=conf/train_realigner.yaml
maxepoch=50

# decoding setup
decode_config=conf/decode.yaml

# decoding parameter
recog_model=model.acc.best  # set a model to be used for decoding: 'model.acc.best' or 'model.loss.best'

# model average setup (only for transformer)
n_average=10                 # the number of ASR models to be averaged
use_valbest_average=false    # if true, the validation `n_average`-best ASR models will be averaged.
                             # if false, the last `n_average` ASR models will be averaged.

# ark file location
datadir=/export/home/librispeech

ngpu=1         # number of gpus ("0" uses cpu, otherwise use gpu)
gpuid=
ncpu=64
seed=0

# bpemode (unigram or bpe)
nbpe=400
bpemode=bpe

# realigner setup
mtlalpha=0.3
num_steps=4
beta=0.0
tau=0.0
droprate=0.1

# Masks for decoder training.
num_mask=0
mask_width=10

# Number of decoding steps.
decode_num_steps=-1
ctc_type=builtin

# exp tag
tag= # tag for managing experiments.
decode_set="dev-clean dev-other test-clean test-other"

# input
feats_type=fbank_pitch
idim=83

# The feature directory created by speech-datasets.
dumpdir=/export/home/speech-datasets/librispeech/asr1/dump/fbank_pitch

. utils/parse_options.sh || exit 1;

export CUDA_VISIBLE_DEVICES=${gpuid}

# Set bash to 'debug' mode, it will exit on :
# -e 'error', -u 'undefined variable', -o ... 'error in pipeline', -x 'print commands',
set -e
set -u
set -o pipefail


train_set=train_960
train_dev=dev-clean

# The training/dev/test fbank_pitch features are generated by the speech-datasets package,
# which alleviates us from generating the json files for inputs.
# This is done by going into the librispeech/asr1/ folder of speech-datasets/, and running
# ./run.sh --feats_type fbank_pitch
# The dumpdir/ directory then contains ark features and text files.
# Also, change the path to cmvn.ark in your preprocess_config into the one prepared by speech-datasets.

mkdir -p data/lang_char/
dict=data/lang_char/${train_set}_${bpemode}${nbpe}_units.txt
bpemodel=data/lang_char/${train_set}_${bpemode}${nbpe}
echo "dictionary: ${dict}"

if [ ${stage} -le 2 ] && [ ${stop_stage} -ge 2 ]; then
    ### Task dependent. You have to check non-linguistic symbols used in the corpus.
    echo "stage 2: Dictionary Preparation"

    echo "<unk> 1" > ${dict} # <unk> must be 1, 0 will be used for "blank" in CTC
    cut -f 2- -d" " ${dumpdir}/train-clean-100/text ${dumpdir}/train-clean-360/text ${dumpdir}/train-other-500/text \
        > data/lang_char/input.txt
    spm_train --input=data/lang_char/input.txt \
              --vocab_size=${nbpe} \
              --model_type=${bpemode} \
              --model_prefix=${bpemodel} \
              --input_sentence_size=100000000

    spm_encode --model=${bpemodel}.model --output_format=piece < data/lang_char/input.txt | tr ' ' '\n' | sort | uniq | awk '{print $0 " " NR+1}' >> ${dict}
    wc -l ${dict}
fi


if [ -z ${tag} ]; then
    expname=${train_set}
    if [ -n "${preprocess_config}" ]; then
	    expname=${expname}_$(basename ${preprocess_config%.*})
    fi
else
    expname=${train_set}_${backend}_${tag}
fi
expname=${expname}_${bpemode}${nbpe}

expname=${expname}_alpha${mtlalpha}_steps${num_steps}_tau${tau}_mask${num_mask}_width${mask_width}_beta${beta}
expdir=exp/${expname}

odim=$(wc -l ${dict} | awk '{print $1}')
odim=$(echo "${odim}+2" | bc)
if [ ${stage} -le 3 ] && [ ${stop_stage} -ge 3 ]; then
    echo "stage 3: Realigner Network Training"
    mkdir -p ${expdir}

    python -u -m torch.distributed.launch --nproc_per_node=${ngpu} --master_port=$RANDOM \
        ../../../espnet/bin/realigner_train.py \
        --config ${train_config} \
        --preprocess-conf ${preprocess_config} \
        --ngpu ${ngpu} \
        --backend ${backend} \
        --outdir ${expdir}/results \
        --tensorboard-dir tensorboard/${expname} \
        --debugmode ${debugmode} \
        --dict ${dict} \
        --debugdir ${expdir} \
        --verbose ${verbose} \
        --seed ${seed} \
        --resume ${resume} \
        --epochs ${maxepoch} \
        --mtlalpha ${mtlalpha} --beta ${beta} \
        --num-steps ${num_steps} \
        --error-temperature ${tau} \
        --ctc_type ${ctc_type} \
        --dropout-rate ${droprate} \
        --decoder-num-mask ${num_mask} --decoder-mask-width ${mask_width} \
        --batch-count seq \
        --train-sets librispeech/train-clean-100,librispeech/train-clean-360,librispeech/train-other-500 \
        --valid-sets librispeech/dev-clean,librispeech/dev-other \
        --precomputed-feats-type ${feats_type} \
        --idim ${idim} --odim ${odim} \
        --text-filename text \
        --spmodel ${bpemodel}.model
fi

if [ ${stage} -le 4 ] && [ ${stop_stage} -ge 4 ]; then
    echo "stage 4: Decoding"
    if [[ $(get_yaml.py ${train_config} model-module) = *transformer* ]]; then
        # Average ASR models
        if ${use_valbest_average}; then
            recog_model=model.val${n_average}.avg.best
            opt="--log ${expdir}/results/log"
        else
            recog_model=model.last${n_average}.avg.best
            opt="--log"
        fi
        average_checkpoints.py \
            ${opt} \
            --backend ${backend} \
            --snapshots ${expdir}/results/snapshot.ep.* \
            --out ${expdir}/results/${recog_model} \
            --num ${n_average}

    fi

    nj=${ncpu}
    pids=() # initialize pids
    for rtask in ${decode_set}; do
    (
        decode_dir=decode_${rtask}_$(basename ${decode_config%.*})_steps${decode_num_steps}

        #### use CPU for decoding
        ngpu=0

        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --config ${decode_config} \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --model ${expdir}/results/${recog_model}  \
            --realigner-num-steps ${decode_num_steps} \
            --num_replicas ${nj} \
            --jobid JOB \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --recog-sets librispeech/${rtask} \
            --precomputed-feats-type ${feats_type} \
            --preprocess-conf ${preprocess_config} \
            --text-filename text \
            --spmodel ${bpemodel}.model

        score_sclite.sh --bpe ${nbpe} --bpemodel ${bpemodel}.model --wer true ${expdir}/${decode_dir} ${dict}

    ) &
    pids+=($!) # store background pids
    done
    i=0; for pid in "${pids[@]}"; do wait ${pid} || ((++i)); done
    [ ${i} -gt 0 ] && echo "$0: ${i} background jobs are failed." && false
    echo "Finished"
fi

# ./run_realigner.sh --stage 2 --stop_stage 2
# ./run_realigner.sh --stage 3 --stop_stage 3 --ngpu 8 --gpuid 0,1,2,3,4,5,6,7 --tag realigner
# ./run_realigner.sh --stage 4 --stop_stage 4 --tag realigner --decode_num_steps 1
